/**************************************************************************
 DBDESCKUNDE.CPP
 **************************************************************************
 Projekt      : ApWare - WinDekis
 Copyright    : SunGard Ambit CRM
 Compiler     : Borland C++
 Beschreibung : Enthält Datenbankbeschreibungslinien des Projekts
                Von ApWare in den Project Ordner kopieren und
                projektspezifisch erweitern
 **************************************************************************

 Datum        Vers   Vis   Beschreibung
 -----        ----   ---   ------------

 27.12.2004   1.00   Ak    1. Ausgabe

 **************************************************************************/


/*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
 {     Tabelle:Nr                           ,TabNr   ,szDBName                        ,OrderBy         ,DefaultDesc       ,nFields   ,szName                                              ,szNameLanguage2                      ,PrimaryKey                                ,Flags                                      ,QueryFlags                                                                                                           },
 {     Feld:Nr                              ,TabNr   ,szDBName                        ,DBType          ,CType             ,Len       ,szName                                              ,szNameLanguage2                      ,ForeignKey                                ,Flags                                      ,QueryFlags                                                                                                           },
 ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/


   {   KUNDE_KUNDENID_ACCNAMELONG           ,KUNDE   ,_T("KUNDENID_ACCNAMELONG")      ,SQL_VARCHAR     ,SQL_C_CHAR        ,180       ,ADD_ZUSATZ_COL(_T("Kunden Id/Bezeichnungvertrag")   ,_T("Client Id/Account name long"))   ,NONE                                      ,DB_NO_DBFIELD|DB_NO_SELECT|DB_AD_EXCLUDE   ,0                                                                                                     ,0             },
   #ifdef __OPENING_APPROVAL__
   {   KUNDE_APPROVAL_STATUS_CD             ,KUNDE   ,_T("APPROVAL_STATUS_CD")        ,SQL_NUMERIC     ,SQL_C_LONG        ,4         ,ADD_ZUSATZ_COL(_T("Approval Status")                ,_T("Approval Status"))               ,APPROVAL_STATUS_STATUS_CD                 ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_CLIENT_STATUS_CD               ,KUNDE   ,_T("CLIENT_STATUS_CD")          ,SQL_VARCHAR     ,SQL_C_CHAR        ,2         ,ADD_ZUSATZ_COL(_T("Client Status")                  ,_T("Client Status"))                 ,CLIENT_STATUS_STATUS_CD                   ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP1_CD              ,KUNDE   ,_T("APPROVAL_STEP1_CD")         ,SQL_VARCHAR     ,SQL_C_CHAR        ,2         ,ADD_ZUSATZ_COL(_T("Step 1 Approval Decision")       ,_T("Step 1 Approval Decision"))      ,JANEIN_LISTE_CD                           ,DB_NOTNULL                                 ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP1_ASSESSMENT_CD   ,KUNDE   ,_T("APPROVAL_STEP1_ASSES_CD")   ,SQL_NUMERIC     ,SQL_C_LONG        ,4         ,ADD_ZUSATZ_COL(_T("Step 1 Approval Assessment")     ,_T("Step 1 Approval Assessment"))    ,APPROVAL_STEP1_ASSESSMENT_ASSESSMENT_CD   ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP1_USER            ,KUNDE   ,_T("APPROVAL_STEP1_USER")       ,SQL_VARCHAR     ,SQL_C_CHAR        ,31        ,ADD_ZUSATZ_COL(_T("Step 1 Approval User")           ,_T("Step 1 Approval User"))          ,MITARBEITER_USERID                        ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP1_DATE            ,KUNDE   ,_T("APPROVAL_STEP1_DATE")       ,SQL_TIMESTAMP   ,SQL_C_TIMESTAMP   ,16        ,ADD_ZUSATZ_COL(_T("Step 1 Approval Date")           ,_T("Step 1 Approval Date"))          ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP1_BEM             ,KUNDE   ,_T("APPROVAL_STEP1_BEM")        ,SQL_VARCHAR     ,SQL_C_CHAR        ,513       ,ADD_ZUSATZ_COL(_T("Step 1 Approval Comment")        ,_T("Step 1 Approval Comment"))       ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP2_CD              ,KUNDE   ,_T("APPROVAL_STEP2_CD")         ,SQL_VARCHAR     ,SQL_C_CHAR        ,2         ,ADD_ZUSATZ_COL(_T("Step 2 Approval Decision")       ,_T("Step 2 Approval Decision"))      ,JANEIN_LISTE_CD                           ,DB_NOTNULL                                 ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP2_ASSESSMENT_CD   ,KUNDE   ,_T("APPROVAL_STEP2_ASSES_CD")   ,SQL_NUMERIC     ,SQL_C_LONG        ,4         ,ADD_ZUSATZ_COL(_T("Step 2 Approval Assessment")     ,_T("Step 2 Approval Assessment"))    ,APPROVAL_STEP2_ASSESSMENT_ASSESSMENT_CD   ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP2_USER            ,KUNDE   ,_T("APPROVAL_STEP2_USER")       ,SQL_VARCHAR     ,SQL_C_CHAR        ,31        ,ADD_ZUSATZ_COL(_T("Step 2 Approval User")           ,_T("Step 2 Approval User"))          ,MITARBEITER_USERID                        ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP2_DATE            ,KUNDE   ,_T("APPROVAL_STEP2_DATE")       ,SQL_TIMESTAMP   ,SQL_C_TIMESTAMP   ,16        ,ADD_ZUSATZ_COL(_T("Step 2 Approval Date")           ,_T("Step 2 Approval Date"))          ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP2_BEM             ,KUNDE   ,_T("APPROVAL_STEP2_BEM")        ,SQL_VARCHAR     ,SQL_C_CHAR        ,513       ,ADD_ZUSATZ_COL(_T("Step 2 Approval Comment")        ,_T("Step 2 Approval Comment"))       ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP3_CD              ,KUNDE   ,_T("APPROVAL_STEP3_CD")         ,SQL_VARCHAR     ,SQL_C_CHAR        ,2         ,ADD_ZUSATZ_COL(_T("Step 3 Approval Decision")       ,_T("Step 3 Approval Decision"))      ,JANEIN_LISTE_CD                           ,DB_NOTNULL                                 ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP3_ASSESSMENT_CD   ,KUNDE   ,_T("APPROVAL_STEP3_ASSES_CD")   ,SQL_NUMERIC     ,SQL_C_LONG        ,4         ,ADD_ZUSATZ_COL(_T("Step 3 Approval Assessment")     ,_T("Step 3 Approval Assessment"))    ,APPROVAL_STEP3_ASSESSMENT_ASSESSMENT_CD   ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP3_USER            ,KUNDE   ,_T("APPROVAL_STEP3_USER")       ,SQL_VARCHAR     ,SQL_C_CHAR        ,31        ,ADD_ZUSATZ_COL(_T("Step 3 Approval User")           ,_T("Step 3 Approval User"))          ,MITARBEITER_USERID                        ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP3_DATE            ,KUNDE   ,_T("APPROVAL_STEP3_DATE")       ,SQL_TIMESTAMP   ,SQL_C_TIMESTAMP   ,16        ,ADD_ZUSATZ_COL(_T("Step 3 Approval Date")           ,_T("Step 3 Approval Date"))          ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP3_BEM             ,KUNDE   ,_T("APPROVAL_STEP3_BEM")        ,SQL_VARCHAR     ,SQL_C_CHAR        ,513       ,ADD_ZUSATZ_COL(_T("Step 3 Approval Comment")        ,_T("Step 3 Approval Comment"))       ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP4_CD              ,KUNDE   ,_T("APPROVAL_STEP4_CD")         ,SQL_VARCHAR     ,SQL_C_CHAR        ,2         ,ADD_ZUSATZ_COL(_T("Step 4 Approval Decision")       ,_T("Step 4 Approval Decision"))      ,JANEIN_LISTE_CD                           ,DB_NOTNULL                                 ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP4_ASSESSMENT_CD   ,KUNDE   ,_T("APPROVAL_STEP4_ASSES_CD")   ,SQL_NUMERIC     ,SQL_C_LONG        ,4         ,ADD_ZUSATZ_COL(_T("Step 4 Approval Assessment")     ,_T("Step 4 Approval Assessment"))    ,APPROVAL_STEP4_ASSESSMENT_ASSESSMENT_CD   ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP4_USER            ,KUNDE   ,_T("APPROVAL_STEP4_USER")       ,SQL_VARCHAR     ,SQL_C_CHAR        ,31        ,ADD_ZUSATZ_COL(_T("Step 4 Approval User")           ,_T("Step 4 Approval User"))          ,MITARBEITER_USERID                        ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP4_DATE            ,KUNDE   ,_T("APPROVAL_STEP4_DATE")       ,SQL_TIMESTAMP   ,SQL_C_TIMESTAMP   ,16        ,ADD_ZUSATZ_COL(_T("Step 4 Approval Date")           ,_T("Step 4 Approval Date"))          ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP4_BEM             ,KUNDE   ,_T("APPROVAL_STEP4_BEM")        ,SQL_VARCHAR     ,SQL_C_CHAR        ,513       ,ADD_ZUSATZ_COL(_T("Step 4 Approval Comment")        ,_T("Step 4 Approval Comment"))       ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP5_CD              ,KUNDE   ,_T("APPROVAL_STEP5_CD")         ,SQL_VARCHAR     ,SQL_C_CHAR        ,2         ,ADD_ZUSATZ_COL(_T("Step 5 Approval Decision")       ,_T("Step 5 Approval Decision"))      ,JANEIN_LISTE_CD                           ,DB_NOTNULL                                 ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP5_ASSESSMENT_CD   ,KUNDE   ,_T("APPROVAL_STEP5_ASSES_CD")   ,SQL_NUMERIC     ,SQL_C_LONG        ,4         ,ADD_ZUSATZ_COL(_T("Step 5 Approval Assessment")     ,_T("Step 5 Approval Assessment"))    ,APPROVAL_STEP5_ASSESSMENT_ASSESSMENT_CD   ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP5_USER            ,KUNDE   ,_T("APPROVAL_STEP5_USER")       ,SQL_VARCHAR     ,SQL_C_CHAR        ,31        ,ADD_ZUSATZ_COL(_T("Step 5 Approval User")           ,_T("Step 5 Approval User"))          ,MITARBEITER_USERID                        ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP5_DATE            ,KUNDE   ,_T("APPROVAL_STEP5_DATE")       ,SQL_TIMESTAMP   ,SQL_C_TIMESTAMP   ,16        ,ADD_ZUSATZ_COL(_T("Step 5 Approval Date")           ,_T("Step 5 Approval Date"))          ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   {   KUNDE_APPROVAL_STEP5_BEM             ,KUNDE   ,_T("APPROVAL_STEP5_BEM")        ,SQL_VARCHAR     ,SQL_C_CHAR        ,513       ,ADD_ZUSATZ_COL(_T("Step 5 Approval Comment")        ,_T("Step 5 Approval Comment"))       ,NONE                                      ,0                                          ,DB_AKTE|DB_KUNDE|DB_OW_KUNDE|DB_DOKU|DB_KORDOK|DB_AMLHITS|DB_PARTNER|DB_KREDITKARTE|DB_SCHLIESSFACH   ,0   ,0   ,0   },
   #endif



